version: '3'

services:
  koel:
    build:
      context: .
    container_name: 'charondev'
    depends_on:
      - database
    ports:
      - 80:80
    env_file:
      - .env.dev
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_DATABASE=charon
      - DB_USERNAME=charon
      - DB_PASSWORD=password
    volumes:
      - music:/music
      - covers:/var/www/html/public/img/covers
      - search_index:/var/www/html/storage/search-indexes
      - ./.env.koel:/var/www/html/.env

  database:
    image: mariadb:10.11
    env_file:
      - .env.dev
    environment:
      - MYSQL_DATABASE=charon
      - MYSQL_USER=charon
      - MYSQL_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=password
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  music:
  covers:
  search_index: