name: Backend Unit Tests
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - resources/assets/**
  push:
    branches:
      - dev
      - main
    paths-ignore:
      - resources/assets/**
  workflow_dispatch:
    branches:
      - dev
      - main
    paths-ignore:
      - resources/assets/**
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 8.1 ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v6
          coverage: xdebug
          extensions: pdo_sqlite, zip, gd
      - name: Install PHP dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: --ignore-platform-reqs
      - name: Generate app key
        run: php artisan key:generate
      - name: Upload logs if broken
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: logs
          path: storage/logs
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}