name: Frontend Unit Tests
on:
  pull_request:
    branches:
      - main
    paths:
      - resources/assets/**
      - .github/workflows/frontend.yml
  push:
    branches:
      - dev
    paths:
      - resources/assets/**
      - .github/workflows/frontend.yml
  workflow_dispatch:
    branches:
      - dev
      - main
    paths:
      - resources/assets/**
      - .github/workflows/frontend.yml

env:
  LARAVEL_BYPASS_ENV_CHECK: 1

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 18 ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Collect coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}